// Konstanta sistem yang digunakan di seluruh aplikasi
// Nilai ini berdasarkan aturan bisnis di 2.Flow-and-Feature.md

// === Batasan Kuantitatif ===
export const MAX_ACTIVE_REPORTS_PER_USER = 3;
export const REPORT_EXPIRY_DAYS = 30;
export const REPORT_PRE_EXPIRY_WARNING_DAYS = 5;

// === File Upload ===
export const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
export const MAX_CATEGORY_IMAGE_SIZE = 2 * 1024 * 1024; // 2MB
export const ACCEPTED_IMAGE_TYPES = ["image/jpeg", "image/png"];

// === Supabase Storage Buckets ===
export const STORAGE_BUCKETS = {
  REPORT_IMAGES: "report-images",
  CLAIM_IMAGES: "claim-images",
  ANNOUNCEMENT_IMAGES: "announcement-images",
  CATEGORY_IMAGES: "category-images",
} as const;

// === Enrollment Code ===
export const ENROLLMENT_CODE_PREFIX = {
  SISWA: "FWD-SISWA",
  GURU: "FWD-GURU",
} as const;

// === Notifikasi Types ===
export const NOTIFICATION_TYPES = {
  REPORT_VERIFIED: "REPORT_VERIFIED",
  REPORT_REJECTED: "REPORT_REJECTED",
  REPORT_NEAR_EXPIRY: "REPORT_NEAR_EXPIRY",
  REPORT_EXPIRED: "REPORT_EXPIRED",
  CLAIM_SUBMITTED: "CLAIM_SUBMITTED",
  CLAIM_APPROVED: "CLAIM_APPROVED",
  CLAIM_REJECTED: "CLAIM_REJECTED",
  CLAIM_COMPLETED: "CLAIM_COMPLETED",
  NEW_COMMENT: "NEW_COMMENT",
  PASSWORD_RESET_PROCESSED: "PASSWORD_RESET_PROCESSED",
} as const;

// === Audit Log Actions ===
export const AUDIT_ACTIONS = {
  USER_REGISTERED: "USER_REGISTERED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_REACTIVATED: "USER_REACTIVATED",
  ADMIN_CREATED: "ADMIN_CREATED",
  PASSWORD_RESET: "PASSWORD_RESET",
  REPORT_CREATED: "REPORT_CREATED",
  REPORT_VERIFIED: "REPORT_VERIFIED",
  REPORT_REJECTED: "REPORT_REJECTED",
  REPORT_EXPIRED: "REPORT_EXPIRED",
  REPORT_DELETED: "REPORT_DELETED",
  CLAIM_SUBMITTED: "CLAIM_SUBMITTED",
  CLAIM_APPROVED: "CLAIM_APPROVED",
  CLAIM_REJECTED: "CLAIM_REJECTED",
  CLAIM_COMPLETED: "CLAIM_COMPLETED",
  ENROLLMENT_CODE_GENERATED: "ENROLLMENT_CODE_GENERATED",
  ENROLLMENT_CODE_DEACTIVATED: "ENROLLMENT_CODE_DEACTIVATED",
  CATEGORY_CREATED: "CATEGORY_CREATED",
  CATEGORY_UPDATED: "CATEGORY_UPDATED",
  CATEGORY_DELETED: "CATEGORY_DELETED",
} as const;
